### ISSUE TITLE
Pinterestbutton doesn´t show

### ISSUE THREAD

**Issue by StudioV19** [fritzmg/contao-sharebuttons#19]
Tried to get share buttons for Facebook, Twitter, Google+ and Pinterest. All shows but NOT Pinterest. I checked the html and there are only 3 list elements. I tried other kombinations and only to pick Pinterest but it seems like all buttons are working but not Pinterest. I checked out the pictures used for the extension but a logo for Pinterest is there.
Is there a bug in the extensions?

**Comment by fritzmg** [comment]
There is an undocumented requirement for the Pinterest button: you must provide an image. If you are using the sharebuttons in your news template via `<?php echo $this->sharebuttons; ?>` the news teaser image is used automatically (or at least it should be).

If you want to provide an image on any other regular page, you can either:

* Use the __social_images__ extension (available in the [ER2](https://contao.org/de/extension-list/view/social_images.en.html) and via [Composer](https://packagist.org/packages/codefog/contao-social_images)) - the pinterest sharebutton will then use the (first) social image defined for the current page automatically
* or insert an absolute URL to an image into `$GLOBALS['SOCIAL_IMAGES'][0]` yourself in a template or some other script _before_ the sharebuttons are generated

**Comment by StudioV19** [comment]
OK, thank you.

**Comment by fritzmg** [comment]
Documentation added in c813abe387f957f44d6774319af55f696f92ea46
