### ISSUE TITLE
Face book and twitter links not working

### ISSUE THREAD

**Issue by 360fusionBen** [fritzmg/contao-sharebuttons#21]
I'm having a problem with the Twitter and Facebook link. the links don't seem to be adding the social media sites address before the link so when you click it it launches a new window but it loads my website page not found page in the window.
could this be because it's on a sub domain?
here is a link: http://belviso.360fusionhosting.co.uk/blog/id-2015-dates-for-ipaf-3a-and-3b-training
All the other share links work fine.

**Comment by fritzmg** [comment]
The default share links for Facebook and Twitter use Contao's `share/index.php`. It seems there is a directive in place on your website, that rewrites or redirects this request and causes a `404 Page not found` response from Contao.

Can you post the content of your `.htaccess`?

If this is not solveable, you could also change the sharer URL for twitter and facebook to their native ones. e.g. instead of
```php
share/index.php?p=facebook&amp;u=<?php echo $this->url; ?>&amp;t=<?php echo $this->title; ?>
```
you could use
```php
http://www.facebook.com/sharer/sharer.php?u=<?php echo $this->url; ?>&amp;t=<?php echo $this->title; ?>
```
And instead of
```php
share/index.php?p=twitter&amp;u=<?php echo $this->url; ?>&amp;t=<?php echo $this->title; ?>
```
you could use
```php
http://twitter.com/share?url=<?php echo $this->url; ?>&amp;text=<?php echo $this->title; ?>
```

**Comment by 360fusionBen** [comment]
Hi,
Thanks for getting abck to me so quickly. I'm not sure why the sharer file would do that, I haven;t made any changes that I know of.
Here is my htaccess file:


##
# Contao Open Source CMS
#
# Copyright (c) 2005-2014 Leo Feyer
#
# @package Core
# @link    https://contao.org
# @license http://www.gnu.org/licenses/lgpl-3.0.html LGPL
##

##
# Prevent access to the Contao template files
##
<FilesMatch "\.(tpl|html5|xhtml)$">
  <IfModule !mod_authz_core.c>
    Order deny,allow
    Deny from all
  </IfModule>
  <IfModule mod_authz_core.c>
    Require all denied
  </IfModule>
</FilesMatch>

##
# Allow access from all domains for webfonts
# @see https://github.com/h5bp/html5-boilerplate
##
<IfModule mod_headers.c>
  <FilesMatch "\.(ttf|ttc|otf|eot|woff|font\.css)$">
    Header set Access-Control-Allow-Origin "*"
  </FilesMatch>
</IfModule>

##
# Disable ETags
# @see http://developer.yahoo.com/performance/rules.html#etags
##
FileETag None
<IfModule mod_headers.c>
  Header unset ETag
</IfModule>

##
# Set the proper MIME types
# @see https://github.com/h5bp/html5-boilerplate
##
<IfModule mod_mime.c>
  AddType application/javascript              js jsonp
  AddType application/json                    json
  AddType audio/ogg                           oga ogg
  AddType audio/mp4                           m4a f4a f4b
  AddType video/ogg                           ogv
  AddType video/mp4                           mp4 m4v f4v f4p
  AddType video/webm                          webm
  AddType video/x-flv                         flv
  AddType image/svg+xml                       svg svgz
  AddEncoding gzip                            svgz
  AddType application/vnd.ms-fontobject       eot
  AddType application/x-font-ttf              ttf ttc
  AddType font/opentype                       otf
  AddType application/x-font-woff             woff
  AddType image/x-icon                        ico
  AddType image/webp                          webp
  AddType text/cache-manifest                 appcache manifest
  AddType text/x-component                    htc
  AddType application/xml                     rss atom xml rdf
  AddType application/x-web-app-manifest+json webapp
  AddType text/x-vcard                        vcf
  AddType application/x-shockwave-flash       swf
</IfModule>

##
# Gzip compression
# @see https://github.com/h5bp/html5-boilerplate
##
<IfModule mod_deflate.c>
  <IfModule mod_filter.c>
    AddOutputFilterByType DEFLATE text/html text/plain text/css application/json
    AddOutputFilterByType DEFLATE application/javascript
    AddOutputFilterByType DEFLATE text/xml application/xml text/x-component
    AddOutputFilterByType DEFLATE application/xhtml+xml application/rss+xml application/atom+xml
    AddOutputFilterByType DEFLATE image/x-icon image/svg+xml application/vnd.ms-fontobject application/x-font-ttf font/opentype
  </IfModule>
</IfModule>

##
# Expires headers (for better cache control)
# @see https://github.com/h5bp/html5-boilerplate
##
<IfModule mod_expires.c>
  ExpiresActive on

  ##
  # Productional website
  ##
  ExpiresByType text/cache-manifest           "access plus 0 seconds"
  ExpiresByType text/html                     "access plus 0 seconds"
  ExpiresByType text/xml                      "access plus 0 seconds"
  ExpiresByType application/xml               "access plus 0 seconds"
  ExpiresByType application/json              "access plus 0 seconds"
  ExpiresByType application/rss+xml           "access plus 1 hour"
  ExpiresByType application/atom+xml          "access plus 1 hour"
  ExpiresByType image/gif                     "access plus 1 month"
  ExpiresByType image/png                     "access plus 1 month"
  ExpiresByType image/jpeg                    "access plus 1 month"
  ExpiresByType image/x-icon                  "access plus 1 month"
  ExpiresByType video/ogg                     "access plus 1 month"
  ExpiresByType audio/ogg                     "access plus 1 month"
  ExpiresByType video/mp4                     "access plus 1 month"
  ExpiresByType video/webm                    "access plus 1 month"
  ExpiresByType text/x-component              "access plus 1 month"
  ExpiresByType application/x-font-ttf        "access plus 1 month"
  ExpiresByType font/opentype                 "access plus 1 month"
  ExpiresByType application/x-font-woff       "access plus 1 month"
  ExpiresByType image/svg+xml                 "access plus 1 month"
  ExpiresByType application/vnd.ms-fontobject "access plus 1 month"
  ExpiresByType text/css                      "access plus 1 year"
  ExpiresByType application/javascript        "access plus 1 year"

  ##
  # Disable caching during development
  # @see https://github.com/contao/core/issues/4364
  ##
  #ExpiresByType text/cache-manifest           "access"
  #ExpiresByType text/html                     "access"
  #ExpiresByType text/xml                      "access"
  #ExpiresByType application/xml               "access"
  #ExpiresByType application/json              "access"
  #ExpiresByType application/rss+xml           "access"
  #ExpiresByType application/atom+xml          "access"
  #ExpiresByType image/gif                     "access"
  #ExpiresByType image/png                     "access"
  #ExpiresByType image/jpeg                    "access"
  #ExpiresByType image/x-icon                  "access"
  #ExpiresByType video/ogg                     "access"
  #ExpiresByType audio/ogg                     "access"
  #ExpiresByType video/mp4                     "access"
  #ExpiresByType video/webm                    "access"
  #ExpiresByType text/x-component              "access"
  #ExpiresByType application/x-font-ttf        "access"
  #ExpiresByType font/opentype                 "access"
  #ExpiresByType application/x-font-woff       "access"
  #ExpiresByType image/svg+xml                 "access"
  #ExpiresByType application/vnd.ms-fontobject "access"
  #ExpiresByType text/css                      "access"
  #ExpiresByType application/javascript        "access"

</IfModule>

##
# Header adjustments
##
<IfModule mod_headers.c>

  ##
  # Disable caching during development
  # @see https://github.com/contao/core/issues/4364
  ##
  #Header unset Cache-Control
  #Header append Cache-Control must-revalidate

  ##
  # Do not cache the cron.txt file
  # @see https://github.com/contao/core/issues/5105
  ##
  <FilesMatch "cron\.txt$">
    Header set Cache-Control "no-cache, no-store, must-revalidate, max-age=0, proxy-revalidate, no-transform"
  </FilesMatch>

  ##
  # Add a Vary Accept-Encoding header for the compressed resources. If you
  # modify the file types above, make sure to change them here accordingly.
  # @see http://developer.yahoo.com/performance/rules.html#gzip
  #
  # Note: If you are using a case-sensitive file system like HFS+ or ext4, you
  # have to change the <FilesMatch> directive as follows:
  #
  # <FilesMatch "\.(?i:js|css|xml|gz|svgz)$">
  #
  # For more information see: https://github.com/contao/core/issues/4364
  ##
  <FilesMatch "\.(js|css|xml|gz|svgz)$">
    Header append Vary Accept-Encoding
  </FilesMatch>

</IfModule>

##
# Disable MultiViews if you are having issues with requests returning the wrong
# page. Requires AllowOverride Options=All,MultiViews to be set here.
# @see https://github.com/contao/core/issues/3521
##
#Options -MultiViews

##
# URL rewriting
##
<IfModule mod_rewrite.c>
  RewriteEngine On

  ##
  # Change the RewriteBase if your Contao installation is in a subdirectoy and
  # the rewrite rules are not working properly. Usage examples:
  #
  #   RewriteBase /contao-3.0.0
  #   RewriteBase /path/to/contao
  #
  # Depending on your server, you might have to remove the line entirely.
  ##
  RewriteBase /

  ##
  # Uncomment the following lines to add "www." to the domain:
  #
  #   RewriteCond %{HTTP_HOST} ^example\.com$ [NC]
  #   RewriteRule (.*) http://www.example.com/$1 [R=301,L]
  #
  # Uncomment the following lines to remove "www." from the domain:
  #
  #   RewriteCond %{HTTP_HOST} ^www\.example\.com$ [NC]
  #   RewriteRule (.*) http://example.com/$1 [R=301,L]
  #
  # Make sure to replace "example.com" with your domain name.
  ##

  ##
  # If you cannot use mod_deflate, uncomment the following lines to load a
  # compressed .gz version of the aggregated Contao JavaScript and CSS files.
  ##
  #AddEncoding gzip .gz
  #<FilesMatch "\.js\.gz$">
  #  AddType "application/javascript" .gz
  #</FilesMatch>
  #<FilesMatch "\.css\.gz$">
  #  AddType "text/css" .gz
  #</FilesMatch>
  #RewriteCond %{HTTP:Accept-encoding} gzip
  #RewriteCond %{REQUEST_FILENAME} \.(js|css)$
  #RewriteCond %{REQUEST_FILENAME}.gz -f
  #RewriteRule ^(.*)$ $1.gz [QSA,L]

  ##
  # By default, Contao adds ".html" to the generated URLs to simulate static
  # HTML documents. If you change the URL suffix in the back end settings, make
  # sure to change it here accordingly!
  #
  #   RewriteRule .*\.html$ index.php [L]   # URL suffix .html
  #   RewriteRule .*\.txt$ index.php [L]    # URL suffix .txt
  #   RewriteRule .*\.json$ index.php [L]   # URL suffix .json
  #
  # If you do not want to use an URL suffix at all, you have to add a second
  # line to prevent URLs that point to folders from being rewritten (see #4031).
  #
  #  RewriteCond %{REQUEST_FILENAME} !-d
  #  RewriteRule .* index.php [L]
  #
  # If you are using mod_cache, it is recommended to use the RewriteRule below,
  # which adds the query string to the internal URL:
  #
  #   RewriteRule (.*\.html)$ index.php/$1 [L]
  #
  # Note that not all environments support mod_rewrite and mod_cache.
  ##
  RewriteCond %{REQUEST_FILENAME} !\.(htm|php|js|css|htc|png|gif|jpe?g|ico|xml|csv|txt|swf|flv|mp4|webm|ogv|mp3|ogg|oga|eot|woff|svg|svgz|ttf|pdf|gz)$
  RewriteCond %{REQUEST_FILENAME} !-f
  RewriteRule .* index.php [L]

  ##
  # The following rules are required if you want to pass the language as first
  # URL parameter (added in Contao 2.11). The first rule rewrites the empty URL
  # to the front end controller, the second one adds a missing trailing slash.
  ##
  RewriteRule ^[a-z]{2}(\-[A-Z]{2})?/$ index.php [L]
  RewriteRule ^([a-z]{2}(\-[A-Z]{2})?)$ $1/ [R=301,L]

</IfModule>

**Comment by fritzmg** [comment]
Yikes, you should put the content of the `.htaccess` file in ``` ;). Or post it on pastebin. Did you make sure, that the file `share/index.php` is existent in your Contao installation?

**Comment by 360fusionBen** [comment]
Hi,

sorry, done that now.

Yep. share file is there.

Ben

**Comment by 360fusionBen** [comment]
In my share/index.php the share links seem to be native?
'''
if (Input::get('p') == 'facebook')
{
	$query  = '?u=' . rawurlencode(Input::get('u', true));
	$query .= '&t=' . rawurlencode(Input::get('t', true));
	$query .= '&display=popup';
	$query .= '&redirect_uri=http%3A%2F%2Fwww.facebook.com';
	header('Location: http://www.facebook.com/sharer/sharer.php' . $query);
	exit;
}


/**
 * Twitter
 */
elseif (Input::get('p') == 'twitter')
{
	$query  = '?url=' . rawurlencode(Input::get('u', true));
	$query .= '&text=' . rawurlencode(Input::get('t', true));
	header('Location: http://twitter.com/share' . $query);
	exit;
}
'''

**Comment by fritzmg** [comment]
Your `.htaccess` has definitely been altered. It contains changes, so that your URLs can be without a suffix (e.g. without the default `.html` suffix). However, the change is incomplete, that's why it's impossible to make a request to `share/index.php` on your website.

**Comment by 360fusionBen** [comment]
I have just replaced the .htaccess file with an unedited original one and changed the rewrite urls to use .html in settings

I'm still having an issue: http://belviso.360fusionhosting.co.uk/blog/id-2015-dates-for-ipaf-3a-and-3b-training.html

**Comment by fritzmg** [comment]
Now http://belviso.360fusionhosting.co.uk/share/index.php ( and http://belviso.360fusionhosting.co.uk/share ) is redirecting to http://belviso.360fusionhosting.co.uk/index.php

**Comment by 360fusionBen** [comment]
Why do all the other share links work and it's only twitter and facebook that don't? Surely if one works they all should?

**Comment by fritzmg** [comment]
> Why do all the other share links work and it's only twitter and facebook that don't? Surely if one works they all should?

No, as I said, the share links for Facebook and Twitter use Contao's own `share/index.php`. As I pointed out you can circumvent the issue by using the native share links for Facebook and Twitter instead (but it would be good to find out why this redirect is happening, since it can potentially cause other issues on your website).

**Comment by 360fusionBen** [comment]
Ok.

Yes, I don need to find that out. hhhmmm. Any ideas?

**Comment by fritzmg** [comment]
Ah sorry, I was mistaken, the `share/index.php` does not create a permanent redirect (well it does, but only if you do not pass any parameters, which is by design) - but now if you try to call http://belviso.360fusionhosting.co.uk/share/index.php?p=facebook&u=http%3A%2F%2Fbelviso.360fusionhosting.co.uk%2Fblog%2Fid-2015-dates-for-ipaf-3a-and-3b-training.html&t=2015%20Dates%20for%20IPAF%203a%20and%203b%20Training! for instance, it results in a 501 Server error. I don't know why this could happen.

Well in any case, here is an altered `sharebuttons_default` template, which uses the native sharer URLs:
```php

<!-- indexer::stop -->
<div class="sharebuttons">
	<ul<?php if( $this->theme ): ?> class="theme <?php echo $this->theme; ?>"<?php endif; ?>>
		<?php if ($this->facebook): ?>
		<li><a class="facebook" href="http://www.facebook.com/sharer/sharer.php?u=<?php echo $this->url; ?>&amp;t=<?php echo $this->title; ?>" rel="nofollow" title="<?php echo $this->lang['share_on_facebook']; ?>" onclick="return shd.open(this.href,600,300);">Facebook</a></li>
		<?php endif; ?>
		<?php if ($this->twitter): ?>
		<li><a class="twitter" href="http://twitter.com/share?url=<?php echo $this->url; ?>&amp;text=<?php echo $this->title; ?>" rel="nofollow" title="<?php echo $this->lang['share_on_twitter']; ?>" onclick="return shd.open(this.href,500,260);">Twitter</a></li>
		<?php endif; ?>
		<?php if ($this->gplus): ?>
		<li><a class="gplus" href="https://plus.google.com/share?url=<?php echo $this->url; ?>" rel="nofollow" title="<?php echo $this->lang['share_on_gplus']; ?>" onclick="return shd.open(this.href,520,450);">Google+</a></li>
		<?php endif; ?>
		<?php if ($this->linkedin): ?>
		<li><a class="linkedin" href="http://www.linkedin.com/shareArticle?mini=true&amp;url=<?php echo $this->url; ?>&amp;title=><?php echo $this->title; ?>" rel="nofollow" title="<?php echo $this->lang['share_on_linkedin']; ?>" onclick="return shd.open(this.href,520,570);">LinkedIn</a></li>
		<?php endif; ?>
		<?php if ($this->xing): ?>
		<li><a class="xing" href="https://www.xing.com/social_plugins/share/new?sc_p=xing-share&amp;h=1&amp;url=<?php echo $this->url; ?>" rel="nofollow" title="<?php echo $this->lang['share_on_xing']; ?>" onclick="return shd.open(this.href,460,460);">Xing</a></li>
		<?php endif; ?>
		<?php if ($this->mail): ?>
		<li><a class="mail" href="mailto:?subject=<?php echo $this->lang['mail_subject']; ?>:%20<?php echo $this->title; ?>&amp;body=<?php echo $this->url; ?>">Mail</a></li>
		<?php endif; ?>
		<?php if ($this->tumblr): ?>
		<li><a class="tumblr" href="http://www.tumblr.com/share?v=3&amp;u=<?php echo $this->url; ?>&amp;t=<?php echo $this->title; ?>&amp;s=<?php echo $this->description; ?>" rel="nofollow" title="<?php echo $this->lang['share_on_tumblr']; ?>" onclick="return shd.open(this.href,800,450);">tumblr</a></li>
		<?php endif; ?>
		<?php if ($this->pinterest && $this->image): ?>
		<li><a class="pinterest" href="http://pinterest.com/pin/create/button/?url=<?php echo $this->url; ?>&amp;media=<?php echo $this->image; ?>&amp;description=<?php echo $this->description; ?>" rel="nofollow" title="<?php echo $this->lang['share_on_pinterest']; ?>" onclick="return shd.open(this.href,460,460);">Pinterest</a></li>
		<?php endif ;?>
		<?php if ($this->reddit): ?>
		<li><a class="reddit" href="http://www.reddit.com/submit?url=<?php echo $this->url; ?>&amp;title=<?php echo $this->title; ?>" rel="nofollow" title="<?php echo $this->lang['share_on_reddit']; ?>" onclick="return shd.open(this.href,855,900);">Reddit</a></li>
		<?php endif; ?>
	</ul>
</div>
<!-- indexer::continue -->
```
Simply create your own `sharebuttons_default` template under _Layout - Templates_ and overwrite its contents with this one.

**Comment by 360fusionBen** [comment]
Thanks, that's works perfectly!

So do I still have an issue with the website and redirects? This could be a bit of a pain.

I know this isn't related to your module but do you know which line to edit in the htaccess file properly so it doesn't use file extensions?

**Comment by fritzmg** [comment]
> So do I still have an issue with the website and redirects? This could be a bit of a pain.

Hm, I don't know, I wouldn't worry about it for now. Just look out for any issues, where parts of Contao are not behaving as they should (modules with redirects or something).

> I know this isn't related to your module but do you know which line to edit in the htaccess file properly so it doesn't use file extensions?

Just replace
```
  RewriteRule .*\.html$ index.php [L]
```
with
```
  RewriteCond %{REQUEST_FILENAME} !-d
  RewriteRule .* index.php [L]
```
(and also remove the URL suffix from the system settings in Contao)

**Comment by 360fusionBen** [comment]
Thanks, that's pretty much what I did before. Thanks for all you help.
