### ISSUE TITLE
Add to events module too

### ISSUE THREAD

**Issue by 360fusionBen** [fritzmg/contao-sharebuttons#22]
Feature request

Can you add this module to the events module as well as the news?

**Comment by fritzmg** [comment]
Well, the problem is, that the events module has no Hook to do the same thing as in the news module. Maybe there is some way to "hack" it in.

But maybe there are workarounds or other solutions for you. Why exactly do you need it?

**Comment by 360fusionBen** [comment]
I can just add the share buttons directly to the events template.

It would just be easier for end clients to manage which sites they want their pages shared on for events if they could just tick boxes like they can in the news channels.

**Comment by fritzmg** [comment]
I see, yes. Well maybe I'll try to hack it in ;)

**Comment by 360fusionBen** [comment]
Cool, Thanks.

**Comment by fritzmg** [comment]
This could be done via the `parseTemplate` Hook, where the Template object is available.

**Comment by fritzmg** [comment]
Implemented in https://github.com/fritzmg/contao-sharebuttons/commit/2f0d6e84dcff27682fbf78a87177c191f27c049b
