### ISSUE TITLE
simple_products compatibility

### ISSUE THREAD

**Issue by sebbo73** [fritzmg/contao-sharebuttons#24]
I use simple_products in my contao (3.52) for my products. after installing sharebuttons all product pages will not be displayed. they appears again when sharebutton is de-installed

**Comment by fritzmg** [comment]
I was unable to reproduce any issue with the `simple_products` extension. However, the `simple_products` extension also uses the `parseArticles` hook, which could cause problems, though not in conjunction with the `sharebuttons` extension. Nevertheless, I released a new version, that takes this into account.

**Comment by sebbo73** [comment]
Well, i have installed it again. Now, it was suvvessful and the products are still visible.
But the buttons won't appear. Maybe i doing something worng. I created a modul set sharebuttons into and add the modul in the article on the postion i want them to be visible. But they are not visible and no sharebutton code is listed in the quellcode.. did i something worng?

**Comment by fritzmg** [comment]
Hard to say. Post screenshots of your module configuration and the content elements.

**Comment by sebbo73** [comment]
![screenshot-absolutsafe de 2016-06-12 19-05-47](https://cloud.githubusercontent.com/assets/19825978/15992627/c75bf260-30d0-11e6-9a0e-94a9ff5cebcf.png)
![screenshot-absolutsafe de 2016-06-12 19-06-11](https://cloud.githubusercontent.com/assets/19825978/15992628/c9f1ca68-30d0-11e6-9297-42cc175c81f2.png)

**Comment by sebbo73** [comment]
do i have to activate any script maybe?

**Comment by fritzmg** [comment]
Yeah, that's odd ;)
