### ISSUE TITLE
URL shows domain twice

### ISSUE THREAD

**Issue by mosesontheweb** [fritzmg/contao-sharebuttons#31]
I just added this module to my webseite and added <?= $this->sharebuttons ?> to my template. The share buttons are shown as configured in the news archive, however, the links for sharing are built a little bit odd.

Example:
`http://www.breitseitcomics.at/share/index.php?p=facebook&u=http%3A%2F%2Fwww.breitseitcomics.at%2Fhttp%3A%2F%2Fwww.breitseitcartoons.at%2Fhome%2Fkunst-und-geschichte.html&t=Kunst%20und%20Geschichte`

Notice the double domain name in the URL, which is provided through the template vars.

Any ideas?

Regards, Thomas

**Comment by fritzmg** [comment]
Hm, I will have a look at it. URL generation has changed in later Contao versions, so this might be why this is happening.

Are only the news URLs affected or also the URLs when you use the Share Buttons content element?

**Comment by mosesontheweb** [comment]
Hallo Fritz,

bin Österreicher. :) Ob das jetzt nur die URLs in den Neuigkeiten betrifft oder auch andere, kann ich leider nicht sagen. Ich habe es jetzt gerade mal in einem News-Template eingebaut, dort ist mir das aufgefallen.

Beste Grüße,

-- 
Thomas Klinger
Dr. Karl Sablik-Straße 22
A-2104 Spillern
M: +43-699-11894386
E: thomas.klinger@me.com

Am 15. März 2017 um 19:49:27, Fritz Michael Gschwantner (notifications@github.com) schrieb:

Hm, I will have a look at it. URL generation has changed in later Contao versions, so this might be why this is happening.

Are only the news URLs affected or also the URLs when you use the Share Buttons content element?

**Comment by fritzmg** [comment]
Should be fixed in c4f34ac
