### ISSUE TITLE
Add "print website" and "pdf"

### ISSUE THREAD

**Issue by k-webdesign** [fritzmg/contao-sharebuttons#36]
Hi,

is it possible to add "print website" and "generate pdf" to replace the core syndication completely if wanted?

**Comment by fritzmg** [comment]
The problem here is that not everyone of these freely available icon sets do have a "print" and "pdf" icon in them. I'll have to build them myself. Or someone needs to build them for me ;)

**Comment by fritzmg** [comment]
For the font awesome themes it's not a problem. It's an issue for the other themes. Sure, I can take the font awesome icon, but I still need to build everything myself ;). Especially for the "Shadow" theme.

**Comment by k-webdesign** [comment]
I see 🤔I'll think about it

**Comment by fritzmg** [comment]
What I can do is make the necessary code and template adjustments only. Then users who use the additional buttons would need to take care of the CSS (and images) themselves. After all, the "Contao" does not support every button either.

**Comment by fritzmg** [comment]
Implemented in 6d4106b5323b83f520a97f3d11969c5f1c3f7dd5

* The _print_ and _pdf_ buttons will not have any icons - except in the Font-Awesome theme of course.
* The _pdf_ button, when used outside of articles, will only print the first found article of the main column of the current page.
* See README for insert tag usage.
