### ISSUE TITLE
WhatsApp is not in output list

### ISSUE THREAD

**Issue by zonky2** [fritzmg/contao-sharebuttons#37]
WhatsApp is checked in module but not in output list

**Comment by fritzmg** [comment]
How did you test? You'll only see it on mobile devices.

**Comment by zonky2** [comment]
ahh - o.k.! 

thx

**Comment by fritzmg** [comment]
But may be this default setting in the template does not make sense anymore. You could have desktop applications for that - or the web app (though I am not sure it can handle whatsapp: links).

**Comment by zonky2** [comment]
... but if you have the desktop app on your computer, the link would be nice anyway

**Comment by zoglo** [comment]
I think this issue can be closed with the newest release :)
