### ISSUE TITLE
The sorting in the module has no effect on the sorting of the output.

### ISSUE THREAD

**Issue by zonky2** [fritzmg/contao-sharebuttons#38]
The sorting in the module has no effect on the sorting of the output.

**Comment by fritzmg** [comment]
Are you using a custom template?

**Comment by zonky2** [comment]
* no theme
* sharebuttons_default

**Comment by zonky2** [comment]
BE
![screenshot_455](https://user-images.githubusercontent.com/1045318/53517717-9a20e880-3acf-11e9-85c2-68aed6d4af47.jpg)

DB
![screenshot_456](https://user-images.githubusercontent.com/1045318/53517724-9e4d0600-3acf-11e9-8d8a-a1dd64a5806f.jpg)

FE
![screenshot_457](https://user-images.githubusercontent.com/1045318/53517729-a311ba00-3acf-11e9-92d1-9176c1c430bf.jpg)

**Comment by zonky2** [comment]
see https://github.com/fritzmg/contao-sharebuttons/pull/40
