### ISSUE TITLE
boxxed theme: print & pdf styles missing

### ISSUE THREAD

**Issue by fritzmg** [fritzmg/contao-sharebuttons#43]
The CSS styles for a.print & a.pdf are missing for the boxxed theme.

**Comment by fritzmg** [comment]
Ah, this theme does not actually have any such icons.

**Comment by samazaphikel** [comment]
Hi, Im using the **light** Theme. there is also a bug in print and PDF. The Icons shows as Twitter

**Comment by fritzmg** [comment]
Yes, the light Theme neither has a PDF nor Print icon. You will have to provide one yourself and set the CSS accordingly.

**Comment by samazaphikel** [comment]
Ok, I will do and for WhatsApp I changed the default template:
```
 <!-- ?php elseif ($network == 'whatsapp' && \Environment::get('agent')->mobile): ? -->
 <?php elseif ($network == 'whatsapp'): ?>
```
