### ISSUE TITLE
Sharebuttons not visible

### ISSUE THREAD

**Issue by bixicy** [fritzmg/contao-sharebuttons#44]
Hi,
by activating sharebuttons in the backend, the buttons are not visible.
![image](https://user-images.githubusercontent.com/46830537/76582282-11a49880-64d6-11ea-8601-e3350e86a8ad.png)

Only visible by inline code like {{sharebuttons::light::facebook:whatsapp:twitter:xing}}

And second, can I change align left to right?

**Comment by fritzmg** [comment]
Where did you activate them?

**Comment by bixicy** [comment]
In Articles and then in the header of one page I have the Sahre buttons like this picture

**Comment by fritzmg** [comment]
> In Articles

Did you follow the instructions? https://github.com/fritzmg/contao-sharebuttons#news-events-articles

>  and then in the header of one page

What do you mean by that?

**Comment by bixicy** [comment]
As I told, I got to **Articles** on the left and go to one page.

And then I go to **Edit** on the header page for this file

![image](https://user-images.githubusercontent.com/46830537/76642094-ead87780-6552-11ea-91eb-9a1a35747220.png)

And inside, I have this settings
![image](https://user-images.githubusercontent.com/46830537/76642160-017ece80-6553-11ea-9077-ea4e0f34ed6e.png)

> Did you follow the instructions? https://github.com/fritzmg/contao-sharebuttons#news-events-articles

Yes, from this page is the example code from my first post

**Comment by fritzmg** [comment]
> Yes, from this page is the example code from my first post

You did not post any example code. Have you customized your article template?

**Comment by bixicy** [comment]
I did, check my first post!

> Only visible by inline code like {{sharebuttons::light::facebook:whatsapp:twitter:xing}}

**Comment by bixicy** [comment]
Additional, on **light** Themeset, for print and pdf it shows the Twitter symbol. And additional for pdf I get on click Error404

**Comment by fritzmg** [comment]
You misunderstood. You need to adjust your `mod_article` template according to the README.

**Comment by bixicy** [comment]
Yes, I have 
![image](https://user-images.githubusercontent.com/46830537/76678956-94178000-65dc-11ea-9479-5b73341f9299.png)

But only visible by InlineCode and not from backend settings

**Comment by fritzmg** [comment]
Which Contao version?

**Comment by bixicy** [comment]
Contao  4.9.1
Contao Manager 1.2.4
PHP Version 7.3.11
ubuntu 19.10.3

**Comment by bixicy** [comment]
Update,

downgrade to Contao 4.9.0, clear chache and update to 4.9.1 solve my problem
