### ISSUE TITLE
Print and pdf icons in sprites missing

### ISSUE THREAD

**Issue by havutcuoglu** [fritzmg/contao-sharebuttons#46]
The print and pdf icons are missing in all themes.
Tested in Contao 4.8 with version 2.1

Check the images below:

![sprites-64-2](https://user-images.githubusercontent.com/11348417/79994730-9e1f7f00-84b6-11ea-9d12-bcc4bacc576c.png)
![sprites-64-1](https://user-images.githubusercontent.com/11348417/79994733-9eb81580-84b6-11ea-8b61-f9e98fce003e.png)
![sprites-64](https://user-images.githubusercontent.com/11348417/79994734-9f50ac00-84b6-11ea-9210-fa889f5b561e.png)
![sprites-32](https://user-images.githubusercontent.com/11348417/79994736-9f50ac00-84b6-11ea-8af8-b5366c5221e5.png)

**Comment by fritzmg** [comment]
See the README. Not all themes support all buttons - since the theme's source does not provide buttons for every option.
