### ISSUE TITLE
unable to override dca sharebuttons_networks options

### ISSUE THREAD

**Issue by jelomada** [fritzmg/contao-sharebuttons#47]
Hi!
Fields `sharebuttons_networks` in your dca files have options from `$GLOBALS['sharebuttons']['networks']`.
And you added that code:
`$GLOBALS['sharebuttons']['networks']['pdf'] = 'create PDF';`
in your language files:
`fritzmg\contao-sharebuttons\system\modules\sharebuttons\languages\de\default.php`
`fritzmg\contao-sharebuttons\system\modules\sharebuttons\languages\en\default.php`
that makes impossible to unset pdf option from `$GLOBALS['sharebuttons']['networks']` in `config.php` file.

**Comment by fritzmg** [comment]
Fixed in 342595b.
