### ISSUE TITLE
$objPage und somit pageTitle leer.

### ISSUE THREAD

**Issue by codepiX-dev** [fritzmg/contao-sharebuttons#5]
Hallo, 
ein sehr schönes und hilfreiches Tool, welches ich gerne auf meiner Webseite einbinden würde. Allerdings habe ich festgestellt, dass zwar die URL richtig gesetzt wird, allerdings immer der Title der Seite fehlt. Im Code habe ich mal versucht mir $objPage auszugeben, diese war leer. Hier scheint also etwas nicht zu stimmen. 

Klasse: ShareButtons.php
Zeile: 44
Code: $objButtonsTemplate->title = $title ?: rawurlencode( $objPage->pageTitle );

Außerdem sehe ich oft, dass im Text zum verteilen, z.B. bei Twitter, noch der Account mit dabei steht. Wäre fein, wenn man das noch mit aufnehmen kann. 

Title, URL, Account
Tesseite http://goggle.de @codepiX

VG
Patrick

**Comment by fritzmg** [comment]
Hm, zu ersterem Problem bräuchte ich genauere Informationen. Welche Contao Version ist das? Passiert das nur bei regulären Seiten oder bspw. in News? Hast du einen Testlink?

Wie genau meinst du das bei Twitter?

**Comment by fritzmg** [comment]
Ok, das Problem mit dem page title habe ich nun gefunden.

**Comment by fritzmg** [comment]
page title fixxed in e93e6c3

**Comment by fritzmg** [comment]
Ich denke ich weiß jetzt was du meinst bei Twitter: du meinst die `via` Angabe. Da dies ja von Website zu Website unterschiedlich ist und es einstweilen ein wenig overkill wäre, das auch noch irgendwo in den Seiteneinstellungen abzuspeichern, wäre es am einfachsten, du machst dir ein eigenes `sharebuttons_default` Template und ersetzt die Zeile
```php
<li><a class="twitter" href="share/index.php?p=twitter&amp;u=<?php echo $this->url; ?>&amp;t=<?php echo $this->title; ?>" rel="nofollow" title="{{label::sharebuttons:share_on_twitter}}" onclick="return shd.open(this.href,500,260);">Twitter</a></li>
```
mit
```php
<li><a class="twitter" href="https://twitter.com/intent/tweet?source=<?php echo $this->url; ?>&amp;text=<?php echo $this->title; ?>&amp;via=TWITTERUSERNAME" rel="nofollow" title="{{label::sharebuttons:share_on_twitter}}" onclick="return shd.open(this.href,500,260);">Twitter</a></li>
```
(ab Version 1.0.7). _TWITTERUSERNAME_ ersetzt nu dann natürlich mit dem Twitter Account der dafür gedacht ist.

**Comment by codepiX-dev** [comment]
Hallo, 
entschuldige bitte meine späte Rückmeldung. War die letzten Tage beruflich unterwegs und kann daher erst jetzt wieder schreiben. 

Danke für die Fehlerbehebung. Leider hat es nicht mein generelles Problem gelöst, denn ich hatte die sharebuttons auf der Unterseite von Nachrichten eingebunden, und zwar als Modul im Layout über den eigentlichen Artikel. Dann ist zwar pageTitle leer, aber im title steht nur der Title der Seite (Seitenstruktur). Das war natürlich auch nicht die Lösung, weil ich dort immer nur "beitrag" drin stehen hatte. 

Ich habe jetzt das Modul unterhalb der Beiträge eingebunden und jetzt ist der pageTitle auch gefüllt, denn dieser wird ja im Element news-reader überschrieben, wie es sein soll. 

Leider klappt auch die via Angabe im Template nicht. Im Link ist sie zwar vorhanden, aber im Fenster zum shared auf Twitter wird es nicht mit eingetragen. Was meinstest Du mit ab Version 1.0.7? 

VG
Patrick

**Comment by fritzmg** [comment]
> Ich habe jetzt das Modul unterhalb der Beiträge eingebunden und jetzt ist der pageTitle auch gefüllt, denn dieser wird ja im Element news-reader überschrieben, wie es sein soll. 

Ja, da erst der Newsreader den richtigen Page Title setzt in diesem Fall geht es auch nicht wirklich anders, wenn du die Share Buttons als Content Element oder Modul einsetzt, zumindest sehe ich aktuell keine Möglichkeit. Alternativ könntest du für die News die Share Buttons direkt im `news_latest` Template mit `<?php echo $this->sharebuttons; ?>` ausgeben lassen.

> Leider klappt auch die via Angabe im Template nicht. Im Link ist sie zwar vorhanden, aber im Fenster zum shared auf Twitter wird es nicht mit eingetragen.

Müsste eigentlich so passen - wie sieht der HTML source aus, der jetzt für deine share buttons ausgegeben wird (bzw. für den Twitter Button)?

> Was meinstest Du mit ab Version 1.0.7? 

[Release 1.0.7](https://github.com/fritzmg/contao-sharebuttons/releases/tag/1.0.7)

**Comment by codepiX-dev** [comment]
Ich habe mal ins Template mod_newsread.html die Share Buttons mit dem $this->sharebuttons; versucht einzubinden, aber es erfolgt keine Ausgabe. 

Du kannst Du dir das auf dieser Seite anschauen: 
http://running.kolei.de/beitrag/laeufer-warum-wie-und-wo-alles-begann.html

Die Seite befindet sich noch um Aufbau. Die Buttons sind ganz unten zu finden.

**Comment by fritzmg** [comment]
> Ich habe mal ins Template mod_newsread.html die Share Buttons mit dem $this->sharebuttons; versucht einzubinden, aber es erfolgt keine Ausgabe. 

Nicht im `mod_newsreader` template, sondern im `news_latest` template.

> Du kannst Du dir das auf dieser Seite anschauen:
http://running.kolei.de/beitrag/laeufer-warum-wie-und-wo-alles-begann.html

Ok, du hast nicht exakt das hinein kopiert, was ich geschrieben habe ;). Du benutzt für das Twitter Share Popup noch `share/index.php` von Contao. Das `share/index.php` script von Contao unterstützt den `via` Parameter nicht. Du musst `https://twitter.com/intent/tweet?source=<?php echo $this->url; ?>&amp;text=<?php echo $this->title; ?>&amp;via=TWITTERUSERNAME` nehmen, und ich denke du musst `@codepix` schreiben, statt nur `codepix`, aber da bin ich mir nicht sicher.

**Comment by codepiX-dev** [comment]
Habe ich auch mal in news_latest versucht, auch wenn ich es in diesem Template gar nicht drin haben wollte. Aber auch hier ist nichts zu sehen:

![Template]
(http://running.kolei.de/files/news_latest.png)

Ach ja. Hatte nicht gesehen, dass sich der komplette Link geändert hatte. Habe nur den Parameter dran gesetzt und das konnte dann nicht funktionieren. Mit der oben genannten Anpassung klappt es aber nun auch richtig. Die Angabe erfolgt aber ohne "@", denn sonst ist es doppelt ;-)

**Comment by fritzmg** [comment]
Hast du in dem jeweiligen News Beitrag auch die Sharebuttons aktiviert? Derzeit ist es so, dass dies für jeden News Beitrag gemacht werden muss (siehe auch in der README unter [News](https://github.com/fritzmg/contao-sharebuttons#news) wie du zumindest per dcaconfig.php default Werte dafür vergeben könntest). In der Version 1.1.0 wird man es über das Newsarchiv steuern können.

> Die Angabe erfolgt aber ohne "@", denn sonst ist es doppelt ;-)

Ok, passt :)

**Comment by codepiX-dev** [comment]
Ja, nach Aktivierung im News Beitrag war die Ausgabe auch in der news_latest zu sehen. Wie gesagt, das nutzt mir an der Stelle nur nicht so viel, denn ich wollte es auf den Nachrichten Unterseite über dem Beitrag haben. Da stehen aber nun mal noch nicht alle Infos zur Verfügung, daher muss es jetzt eben unten gehen. Das ist auch in Ordnung, denn nach dem Lesen scrollt man ungerne wieder nach oben um die sharen, das macht man dann eher am Ende der Seite. 

Danke für Deinen tollen Support :)

**Comment by codepiX-dev** [comment]
Sorry, noch mal ich. Leider fehlt mir jetzt im PopUp beim Twitter der Link, also die URL. Wird dort nicht mehr angezeigt, keine Ahnung warum.

**Comment by codepiX-dev** [comment]
Habe mir mal die https://dev.twitter.com/web/tweet-button/web-intent angesehen. Dort steht als Parameter url= und nicht source= 

Nach Änderung klappt das nun auch mit der URL wieder.

**Comment by fritzmg** [comment]
> Ja, nach Aktivierung im News Beitrag war die Ausgabe auch in der news_latest zu sehen. Wie gesagt, das nutzt mir an der Stelle nur nicht so viel, denn ich wollte es auf den Nachrichten Unterseite über dem Beitrag haben.

Hm, naja aber das sollte doch möglich sein bei dir, wenn du es im `news_full` Template direkt vor der Überschrift einfügst. Bzw. direkt nach
```php
<div class="layout_full block<?php echo $this->class; ?>">
```

> Das ist auch in Ordnung, denn nach dem Lesen scrollt man ungerne wieder nach oben um die sharen, das macht man dann eher am Ende der Seite. 

Ja, aber Menschen teilen sachen oft bevor sie alles gelesen haben - oder überhaupt mehr als die Überschrift gelesen haben :D Da gab's auch mal einen interessanten Artikel auf alistapart.com dazu, finde ich nur gerade nicht. Ist aber schon sehr alt.

> Sorry, noch mal ich. Leider fehlt mir jetzt im PopUp beim Twitter der Link, also die URL. Wird dort nicht mehr angezeigt, keine Ahnung warum. 

Hm, also [hier](http://running.kolei.de/beitrag/laeufer-warum-wie-und-wo-alles-begann.html) geht's aktuell, oder?

> Danke für Deinen tollen Support :)

Kein Problem ;)

**Comment by fritzmg** [comment]
> Habe mir mal die https://dev.twitter.com/web/tweet-button/web-intent angesehen. Dort steht als Parameter url= und nicht source=
Nach Änderung klappt das nun auch mit der URL wieder.

Oh ok, gut zu wissen. Hatte die URL von hier genommen: https://github.com/fourtonfish/SimpleSharingButtons/blob/master/share-buttons-color.html

**Comment by codepiX-dev** [comment]
Klasse, das mit news_full klappt wirklich super, jetzt habe ich es wieder nach oben gezogen. Du bist gut ;-) 

Kannst Du mir evtl. auch noch sagen wie ich es jetzt auf den anderen Seiten, also in normalen Artikeln wieder nach oben bekommen? Meine Idee wäre jetzt hier, ein eigenes Layout zu erstellen, in dem ich das Modul ShareButtons wieder einfüge und für die Unterseiten der Nachrichten ein Layout ohne das Modul, damit ich es nicht doppelt einbinde.

**Comment by fritzmg** [comment]
Ja, genau so würde ich's machen ;)

**Comment by fritzmg** [comment]
Notfalls könntest du auf der Newsreader seite das andere Modul auch einfach per `display:none;` verstecken, wenn dir das nicht zu unsauber ist..

**Comment by codepiX-dev** [comment]
Löse es mit den Layouts, finde ich besser zum einstellen und wieder zu nutzen. Jetzt reicht's aber, genug für heute. Wünsche einen schönen Abend 

:+1:

**Comment by fritzmg** [comment]
Ab Version [1.1.1](https://github.com/fritzmg/contao-sharebuttons/tree/1.1.1) könntest du nun wieder dasselbe Layout im Newsreader verwenden und `<?php echo $this->sharebuttons; ?>` aus dem `news_full` Template entfernen :). Siehe #17
