### ISSUE TITLE
FE module shows 'Unknown option' instead of 'PDF'

### ISSUE THREAD

**Issue by Aybee** [fritzmg/contao-sharebuttons#51]
version 2.2.1
Contao 4.11.2

Regards the field 'sharebuttons_networks'. Unfortunately I cannot find the cause.

If I change the options_callback https://github.com/fritzmg/contao-sharebuttons/blob/master/system/modules/sharebuttons/dca/tl_module.php#L28 to this:
```php
...
  'options' => array(
  	'facebook' => 'Facebook',
  	'twitter' => 'Twitter',
  	'linkedin' => 'LinkedIn',
  	'xing' => 'Xing',
  	'mail' => 'E-Mail',
  	'tumblr' => 'tumblr',
  	'pinterest' => 'Pinterest',
  	'reddit' => 'Reddit',
  	'whatsapp' => 'WhatsApp',
  	'print' => 'Print',
  	'pdf' => 'PDF'
  ),
...
```
Then everything's fine.

**Comment by fritzmg** [comment]
This is deliberate, as the PDF share button is supposed to be available only for the content element and for the article setting, see https://github.com/fritzmg/contao-sharebuttons/issues/48. As mentioned there the current implementation would need to be reworked to also work with the front end module.

**Comment by Aybee** [comment]
Ok, thank you. So we will wait till it comes in a future version.
