### ISSUE TITLE
Template is always the default one

### ISSUE THREAD

**Issue by xApep** [fritzmg/contao-sharebuttons#56]
When you create a new template and select it, nothing happens. It always takes _default one.

![image](https://github.com/fritzmg/contao-sharebuttons/assets/1315340/283c37d6-4405-428b-9288-e9acbcf3ebc5)

**Comment by fritzmg** [comment]
I cannot reproduce the issue. However, I only tested with the content element, as your description is missing exact reproduction steps. If this issue still occurs, please provide more detailed reproduction steps.

**Comment by xApep** [comment]
To reproduce it:
1. Copy sharebuttons_default.html5. Paste it into root /templates and rename it.
2. Create News archive
3. Select options for Share as above and select newly created template
4. Save
5. Edit anything within newly create template and you will see no effect

**Comment by fritzmg** [comment]
I also cannot reproduce it this way. The custom template will be output:

```html
<div class="mod_newslist block">
  <!-- TEMPLATE START: templates/news_latest.html5 -->
  <div class="layout_latest arc_1 block first even"> 
    <!-- … -->
    <!-- TEMPLATE START: templates/sharebuttons_foobar.html5 -->
      <!-- … -->
    <!-- TEMPLATE END: templates/sharebuttons_foobar.html5 -->
  </div>
</div>
```
