### ISSUE TITLE
Incorrect attribution for Flat Web Icon Set

### ISSUE THREAD

**Issue by fourtonfish** [fritzmg/contao-sharebuttons#6]
Hi,

The correct attribution for the Flat Web Icon Set should go to [iconsandcoffee.com](http://iconsandcoffee.com/) -- here's the [original source](http://iconsandcoffee.com/freebie-flat-web-icon-set/).

**Comment by fritzmg** [comment]
Thx for pointing that out, attributions are updated in the README now!
