### ISSUE TITLE
Pinterest Plugin braucht Absicherung durch Einverständnis?

### ISSUE THREAD

**Issue by grashalm4u** [fritzmg/contao-sharebuttons#60]
Hallo Fritz,

habe spaßeshalber mal die URL meiner Website [https://die-schreibmaus.de](https://die-schreibmaus.de) beim Website-Scanner von e-Recht 24 auf Tauglichkeit und Rechtssicherheit meiner Seite eingegeben, und u.a. kam das heraus:

"Pinterest Plugin

Über den Einsatz wird in der Datenschutzerklärung informiert. Der Dienst überträgt möglicherweise personenbezogene Daten in unsichere Drittstaaten. Diesen Datentransfer sollten Sie über Ihre Datenschutzerklärung und eine Einwilligung absichern. Dieses Tool können Sie auch lokal auf eigenen Servern betreiben. Dann werden keine Daten an Dritte übertragen.Wir raten dazu, dieses Tool nur im Zusammenhang mit der Shariff- bzw. Zwei-Klick-Lösung einzusetzen, um eine Datenübertragung an den Anbieter erst nach Nutzerinteraktion zu ermöglichen." 

Seltsamerweise moniert er das nur für das Pinterest-Icon. Theoretisch müssten doch von dem Problem auch weitere Dienste der Sharebutton-Icons  betroffen sein, oder nicht?
Ich meine allerdings mich zu erinnern, dass sämtliche Übertragung von Daten zu den Diensten der gezeigten Buttons erst nach dem Anklicken eines Buttons geschieht, und nicht bereits vorher. Ist das richtig? Falls ja, kann ich dann die Warnung von eRecht 24 getrost vernachlässigen, oder ist hier dennoch Handlungsbedarf nötig? Und falls ja, wie sollte ich hier am besten vorgehen?

grashalm

**Comment by fritzmg** [comment]
This extension does not use a Pinterest plugin.

**Comment by grashalm4u** [comment]
That means: the sharehuttons only use an icon with a link, but no plugin? Then can I ignore the warning of the eRecht24 scanner?

**Comment by fritzmg** [comment]
> That means: the sharehuttons only use an icon with a link, but no plugin?

Correct.

> Then can I ignore the warning of the eRecht24 scanner?

That I cannot tell you. You should get to the bottom of this, may be with support from eRecht24.
