### ISSUE TITLE
Installation unter 5.3.x nicht möglich - 

### ISSUE THREAD

**Issue by codesache** [fritzmg/contao-sharebuttons#61]
Contao Manager meldet:

contao-community-alliance/composer-plugin contains a Composer plugin which   
  is blocked by your allow-plugins config. You may add it to the list if you   
  consider it safe.                                                            
  You can run "composer config --no-plugins allow-plugins.contao-community-al  
  liance/composer-plugin [true|false]" to enable it (true) or disable it expl  
  icitly and suppress this exception (false)

**Comment by fritzmg** [comment]
This has nothing to do with this extension. This is related to the `composer.json` of your project.

**Comment by codesache** [comment]
Die Zeile  "contao-components/installer": true, hatte lokal gefehlt. 



"config": {
        "allow-plugins": {
            "contao-components/installer": true,
            "php-http/discovery": true,
            "contao/manager-plugin": true,
            "contao-community-alliance/composer-plugin": true
        }
